#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.
cp ~/app-root/data/parameters.yml ~/app-root/runtime/repo/app/config
cd ~/app-root/runtime/repo/
php ~/app-root/data/composer.phar install
php ~/app-root/data/composer.phar update -o
